//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace charmsmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assortiment
    {
        public int Id { get; set; }
        public string название { get; set; }
        public string цена_ { get; set; }
        public string объем { get; set; }
        public string производитель_ { get; set; }
        public string страна_ { get; set; }
        public Nullable<System.DateTime> дата_призводства { get; set; }
        public string артикул { get; set; }
        public string количество { get; set; }
    }
}
